name: Deploy Azure Infrastructure

on:
  push:
    branches:
      - updating-powershell

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Extract Subscription ID
        id: get-sub
        run: |
          echo "SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)" >> $GITHUB_ENV

      - name: Deploy Bicep template
        env:
          AZURE_AUTOMATION_ACCOUNT: ${{ secrets.AZURE_AUTOMATION_ACCOUNT }}
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_CONTAINER_NAME: ${{ vars.AZURE_CONTAINER_NAME }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
        run: |
          az account set --subscription "$SUBSCRIPTION_ID"
          az deployment group create \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --template-file infra/deploy-resources.bicep \
            --parameters \
                location="$AZURE_LOCATION" \
                automationAccountName="$AZURE_AUTOMATION_ACCOUNT" \
                resourceGroupName="$AZURE_RESOURCE_GROUP" \
                containerName="$AZURE_CONTAINER_NAME" \
                storageAccountName="$AZURE_STORAGE_ACCOUNT_NAME"
