name: Deploy Runbook Vars

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/deploy-automation-vars.yml

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}     
    
      - name: Extract Subscription ID
        id: get-sub
        run: |
          SUBSCRIPTION_ID=$(echo '${{ secrets.AZURE_CREDENTIALS }}' | jq -r .subscriptionId)
          echo "AZURE_SUBSCRIPTION_ID=$SUBSCRIPTION_ID" >> $GITHUB_ENV

      - name: Get Storage Account Key
        env:
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
        run: |
          ACCOUNT_KEY=$(az storage account keys list --account-name "$AZURE_STORAGE_ACCOUNT_NAME" --resource-group "$AZURE_RESOURCE_GROUP" --query '[0].value' -o tsv)
          echo "AZURE_STORAGE_ACCOUNT_KEY=$ACCOUNT_KEY" >> $GITHUB_ENV
          
      - name: Create Automation Account Variables
        env:
          AZURE_AUTOMATION_ACCOUNT: ${{ secrets.AZURE_AUTOMATION_ACCOUNT }}
          AZURE_RESOURCE_GROUP: ${{ vars.AZURE_RESOURCE_GROUP }}
          AZURE_LOCATION: ${{ vars.AZURE_LOCATION }}
          AZURE_CONTAINER_NAME: ${{ vars.AZURE_CONTAINER_NAME }}
          AZURE_STORAGE_ACCOUNT_NAME: ${{ vars.AZURE_STORAGE_ACCOUNT_NAME }}
          AZURE_SUBSCRIPTION_ID: ${{ env.SUBSCRIPTION_ID }}
        uses: azure/powershell@v1
        with:
          azPSVersion: 'latest'
          inlineScript: |            # Install and import required modules
            Install-Module -Name Az.Accounts -Force -Scope CurrentUser
            Install-Module -Name Az.Automation -Force -Scope CurrentUser
            Import-Module Az.Accounts
            Import-Module Az.Automation
            
            # Debug information to help diagnose issues
            Write-Host "Resource Group: $env:AZURE_RESOURCE_GROUP"
            Write-Host "Automation Account: $env:AZURE_AUTOMATION_ACCOUNT"
            Write-Host "Storage Account Name: $env:AZURE_STORAGE_ACCOUNT_NAME"
            Write-Host "Container Name: $env:AZURE_CONTAINER_NAME"
            
            # Explicitly connect to Azure using service principal
            try {
                Write-Host "Connecting to Azure..."
                $creds = ConvertFrom-Json -InputObject '${{ secrets.AZURE_CREDENTIALS }}'
                $securePassword = ConvertTo-SecureString $creds.clientSecret -AsPlainText -Force
                $credential = New-Object System.Management.Automation.PSCredential ($creds.clientId, $securePassword)
                
                Connect-AzAccount -ServicePrincipal -Credential $credential -Tenant $creds.tenantId -Subscription $creds.subscriptionId
                
                Write-Host "Connected to Azure successfully"
            }
            catch {
                Write-Error "Failed to connect to Azure: $_"
                throw $_
            }
            
            # Use $env: prefix to access environment variables in PowerShell
            try {
                Write-Host "Creating Automation Variable: GitHubToken"
                New-AzAutomationVariable -ResourceGroupName $env:AZURE_RESOURCE_GROUP -AutomationAccountName $env:AZURE_AUTOMATION_ACCOUNT -Name "GitHubToken" -Value "${{ secrets.REPO_PAT }}" -Encrypted $true                Write-Host "Creating Automation Variable: StorageAccountName"
                New-AzAutomationVariable -ResourceGroupName $env:AZURE_RESOURCE_GROUP -AutomationAccountName $env:AZURE_AUTOMATION_ACCOUNT -Name "StorageAccountName" -Value $env:AZURE_STORAGE_ACCOUNT_NAME -Encrypted $false
                
                Write-Host "Creating Automation Variable: StorageAccountKey"
                New-AzAutomationVariable -ResourceGroupName $env:AZURE_RESOURCE_GROUP -AutomationAccountName $env:AZURE_AUTOMATION_ACCOUNT -Name "StorageAccountKey" -Value $env:AZURE_STORAGE_ACCOUNT_KEY -Encrypted $true
                
                Write-Host "Creating Automation Variable: ContainerName"
                New-AzAutomationVariable -ResourceGroupName $env:AZURE_RESOURCE_GROUP -AutomationAccountName $env:AZURE_AUTOMATION_ACCOUNT -Name "ContainerName" -Value $env:AZURE_CONTAINER_NAME -Encrypted $false
                
                Write-Host "All variables created successfully"
            }
            catch {
                Write-Error "Failed to create automation variables: $_"
                Write-Error $_.Exception.Message
                Write-Error $_.ScriptStackTrace
                throw $_
            }
          failOnStandardError: true